// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace MyFishEye.Entities.Migrations
{
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class SecondShoot : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SecondShoot));
        
        string IMigrationMetadata.Id
        {
            get { return "201412081443473_SecondShoot"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
